### ISSUE TITLE
error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Shekelme** [Moondex/MasterNodeSetupGuide#1]
I can't install masternode on Ubuntu 18.04 LTS:

`moondex-cli getmininginfo:
/root/moondex/moondex-cli: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
Masternode status:
/root/moondex/moondex-cli: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
`

Meanwhile libboost-all-dev (so as libboost-system-dev) is already installed by default (1.65.1.0ubuntu1).

**Comment by MoondexDev** [comment]
Hi there, We currently only support Ubuntu 16.04. Please install the masternode on a Ubuntu 16.04 instance. Thanks.
